### ISSUE TITLE
Cannot use when change default ssl port 

### ISSUE THREAD

**Issue by paulohmoraes** [callawaywilson/metabasecloner#2]
Host enabled ssl on no default port

Connecting to 'teste.world:8080'
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:631:8)
Emitted 'error' event at:
    at RedirectableRequest.<anonymous> (E:\metabaseapp\metabasecloner-master\node_modules\node-rest-client\lib\node-rest-client.js:721:39)
    at RedirectableRequest.emit (events.js:182:13)
    at ClientRequest.eventHandlers.(anonymous function) (E:\metabaseapp\metabasecloner-master\node_modules\follow-redirects\index.js:16:24)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:391:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by callawaywilson** [comment]
There's not currently an option to specify the port (hostname is just the host).  Adding a port option wouldn't be difficult, would merge a PR.
